language: perl
perl:
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"

before_install:
    # This line should try to match what's in our README.md
    - sudo apt-get install libzmq3-dev libexpat-dev libnet-ssleay-perl libnet-libidn-perl libcrypt-ssleay-perl cpanminus make liblocal-lib-perl

install:

    # ZMQ requires us to specify at build-time what back-end
    # we'll use. Travis comes with ZMQ3 pre-installed.
    - export PERL_ZMQ_BACKEND=ZMQ::LibZMQ3

    - cpanm --notest --skip-satisfied Dist::Zilla

    - dzil authordeps | cpanm --notest --skip-satisfied
    - dzil listdeps   | cpanm --notest --skip-satisfied

script:
    - dzil test --all
