language: perl
perl:
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"

before_install:
    - sudo apt-get update -qq

    # This line should always match what's in our README.md
    - sudo apt-get install -qq libzmq-dev libexpat-dev libnet-ssleay-perl libnet-libidn-perl libcrypt-ssleay-perl cpanminus make liblocal-lib-perl libmethod-signatures-perl

install:
    - cpanm --notest --skip-satisfied Dist::Zilla
    - dzil authordeps | cpanm --notest --skip-satisfied
    - dzil listdeps   | cpanm --notest --skip-satisfied

script:
    - dzil test --all
